export const qmkToReadableKeycodeMapping: Record<string, string> = {
  KC_A: 'A',
  KC_B: 'B',
  KC_C: 'C',
  KC_D: 'D',
  KC_E: 'E',
  KC_F: 'F',
  KC_G: 'G',
  KC_H: 'H',
  KC_I: 'I',
  KC_J: 'J',
  KC_K: 'K',
  KC_L: 'L',
  KC_M: 'M',
  KC_N: 'N',
  KC_O: 'O',
  KC_P: 'P',
  KC_Q: 'Q',
  KC_R: 'R',
  KC_S: 'S',
  KC_T: 'T',
  KC_U: 'U',
  KC_V: 'V',
  KC_W: 'W',
  KC_X: 'X',
  KC_Y: 'Y',
  KC_Z: 'Z',
  KC_1: '1',
  KC_2: '2',
  KC_3: '3',
  KC_4: '4',
  KC_5: '5',
  KC_6: '6',
  KC_7: '7',
  KC_8: '8',
  KC_9: '9',
  KC_0: '0',

  // Function Keys
  KC_F1: 'F1',
  KC_F2: 'F2',
  KC_F3: 'F3',
  KC_F4: 'F4',
  KC_F5: 'F5',
  KC_F6: 'F6',
  KC_F7: 'F7',
  KC_F8: 'F8',
  KC_F9: 'F9',
  KC_F10: 'F10',
  KC_F11: 'F11',
  KC_F12: 'F12',
  KC_F13: 'F13',
  KC_F14: 'F14',
  KC_F15: 'F15',
  KC_F16: 'F16',
  KC_F17: 'F17',
  KC_F18: 'F18',
  KC_F19: 'F19',
  KC_F20: 'F20',
  KC_F21: 'F21',
  KC_F22: 'F22',
  KC_F23: 'F23',
  KC_F24: 'F24',

  // Modifier Keys
  KC_LCTL: 'LCtrl',
  KC_LSFT: 'LShift',
  KC_LALT: 'LAlt',
  KC_LGUI: 'LMeta',
  KC_RCTRL: 'RCtrl',
  KC_RSFT: 'RShift',
  KC_RALT: 'RAlt',
  KC_RGUI: 'RMeta',

  // Navigation Keys
  KC_LEFT: '⬅︎',
  KC_RIGHT: '➡︎',
  KC_UP: '⬆︎',
  KC_DOWN: '⬇︎',
  KC_PGUP: 'PgUp',
  KC_PGDN: 'PgDn',
  KC_HOME: 'Home',
  KC_END: 'End',

  KC_ENT: 'Enter',
  KC_ESC: 'Esc',
  KC_BSPC: 'Bck',
  KC_TAB: 'Tab',
  KC_SPACE: 'Space',
  KC_MINUS: '-',
  KC_EQUAL: '=',
  KC_LBRACKET: '[',
  KC_RBRACKET: ']',
  KC_BSLASH: '\\',
  KC_NONUS_HASH: '#',
  KC_SCOLON: ';',
  KC_QUOT: "'",
  KC_GRAVE: '`',
  KC_COMMA: ',',
  KC_DOT: '.',
  KC_SLASH: '/',
  KC_CAPSLOCK: 'Caps',

  KC_TRNS: '____',
}
