export const qmkToJsKeycodeMapping = {
  // Alphanumeric Keys
  KC_A: 'KeyA',
  KC_B: 'KeyB',
  KC_C: 'KeyC',
  KC_D: 'KeyD',
  KC_E: 'KeyE',
  KC_F: 'KeyF',
  KC_G: 'KeyG',
  KC_H: 'KeyH',
  KC_I: 'KeyI',
  KC_J: 'KeyJ',
  KC_K: 'KeyK',
  KC_L: 'KeyL',
  KC_M: 'KeyM',
  KC_N: 'KeyN',
  KC_O: 'KeyO',
  KC_P: 'KeyP',
  KC_Q: 'KeyQ',
  KC_R: 'KeyR',
  KC_S: 'KeyS',
  KC_T: 'KeyT',
  KC_U: 'KeyU',
  KC_V: 'KeyV',
  KC_W: 'KeyW',
  KC_X: 'KeyX',
  KC_Y: 'KeyY',
  KC_Z: 'KeyZ',
  KC_1: 'Digit1',
  KC_2: 'Digit2',
  KC_3: 'Digit3',
  KC_4: 'Digit4',
  KC_5: 'Digit5',
  KC_6: 'Digit6',
  KC_7: 'Digit7',
  KC_8: 'Digit8',
  KC_9: 'Digit9',
  KC_0: 'Digit0',

  // Function Keys
  KC_F1: 'F1',
  KC_F2: 'F2',
  KC_F3: 'F3',
  KC_F4: 'F4',
  KC_F5: 'F5',
  KC_F6: 'F6',
  KC_F7: 'F7',
  KC_F8: 'F8',
  KC_F9: 'F9',
  KC_F10: 'F10',
  KC_F11: 'F11',
  KC_F12: 'F12',
  KC_F13: 'F13',
  KC_F14: 'F14',
  KC_F15: 'F15',
  KC_F16: 'F16',
  KC_F17: 'F17',
  KC_F18: 'F18',
  KC_F19: 'F19',
  KC_F20: 'F20',
  KC_F21: 'F21',
  KC_F22: 'F22',
  KC_F23: 'F23',
  KC_F24: 'F24',

  // Modifier Keys
  KC_LCTRL: 'ControlLeft',
  KC_LSHIFT: 'ShiftLeft',
  KC_LALT: 'AltLeft',
  KC_LGUI: 'MetaLeft',
  KC_RCTRL: 'ControlRight',
  KC_RSHIFT: 'ShiftRight',
  KC_RALT: 'AltRight',
  KC_RGUI: 'MetaRight',

  // Navigation Keys
  KC_LEFT: 'ArrowLeft',
  KC_RIGHT: 'ArrowRight',
  KC_UP: 'ArrowUp',
  KC_DOWN: 'ArrowDown',
  KC_PGUP: 'PageUp',
  KC_PGDN: 'PageDown',
  KC_HOME: 'Home',
  KC_END: 'End',

  // Numpad Keys
  KC_NUMLOCK: 'NumLock',
  KC_KP_SLASH: 'NumpadDivide',
  KC_KP_ASTERISK: 'NumpadMultiply',
  KC_KP_MINUS: 'NumpadSubtract',
  KC_KP_PLUS: 'NumpadAdd',
  KC_KP_ENTER: 'NumpadEnter',
  KC_KP_1: 'Numpad1',
  KC_KP_2: 'Numpad2',
  KC_KP_3: 'Numpad3',
  KC_KP_4: 'Numpad4',
  KC_KP_5: 'Numpad5',
  KC_KP_6: 'Numpad6',
  KC_KP_7: 'Numpad7',
  KC_KP_8: 'Numpad8',
  KC_KP_9: 'Numpad9',
  KC_KP_0: 'Numpad0',
  KC_KP_DOT: 'NumpadDecimal',

  // Special Keys
  KC_ESC: 'Escape',
  KC_TAB: 'Tab',
  KC_ENTER: 'Enter',
  KC_BSPACE: 'Backspace',
  KC_SPACE: 'Space',
  KC_CAPSLOCK: 'CapsLock',

  // Other Keys (some might not have direct equivalents)
  // Add as needed
}
